# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assessment3GUIv2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 755)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.exp1All = QtWidgets.QStackedWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.exp1All.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(14)
        self.exp1All.setFont(font)
        self.exp1All.setAutoFillBackground(True)
        self.exp1All.setObjectName("exp1All")
        self.welcmPg = QtWidgets.QWidget()
        self.welcmPg.setObjectName("welcmPg")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.welcmPg)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rr = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.rr.setFont(font)
        self.rr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rr.setObjectName("rr")
        self.gridLayout_7.addWidget(self.rr, 1, 3, 1, 1)
        self.oo = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.oo.setFont(font)
        self.oo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.oo.setObjectName("oo")
        self.gridLayout_7.addWidget(self.oo, 1, 5, 1, 1)
        self.wlcNext = QtWidgets.QPushButton(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.wlcNext.setFont(font)
        self.wlcNext.setObjectName("wlcNext")
        self.gridLayout_7.addWidget(self.wlcNext, 3, 0, 1, 8)
        self.pp = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.pp.setFont(font)
        self.pp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pp.setObjectName("pp")
        self.gridLayout_7.addWidget(self.pp, 1, 6, 1, 1)
        self.ss = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.ss.setFont(font)
        self.ss.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ss.setObjectName("ss")
        self.gridLayout_7.addWidget(self.ss, 1, 1, 1, 1)
        self.consentTitle_2 = QtWidgets.QLabel(self.welcmPg)
        self.consentTitle_2.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.consentTitle_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setUnderline(False)
        self.consentTitle_2.setFont(font)
        self.consentTitle_2.setAutoFillBackground(True)
        self.consentTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.consentTitle_2.setObjectName("consentTitle_2")
        self.gridLayout_7.addWidget(self.consentTitle_2, 0, 0, 1, 8)
        self.tt = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.tt.setFont(font)
        self.tt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tt.setObjectName("tt")
        self.gridLayout_7.addWidget(self.tt, 1, 2, 1, 1)
        self.OO = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.OO.setFont(font)
        self.OO.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OO.setObjectName("OO")
        self.gridLayout_7.addWidget(self.OO, 1, 4, 1, 1)
        self.task = QtWidgets.QLabel(self.welcmPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.task.setFont(font)
        self.task.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task.setObjectName("task")
        self.gridLayout_7.addWidget(self.task, 2, 0, 1, 8)
        self.exp1All.addWidget(self.welcmPg)
        self.cnstPg = QtWidgets.QWidget()
        self.cnstPg.setObjectName("cnstPg")
        self.gridLayout = QtWidgets.QGridLayout(self.cnstPg)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.cnstPg)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.consentBox = QtWidgets.QPushButton(self.cnstPg)
        self.consentBox.setObjectName("consentBox")
        self.gridLayout.addWidget(self.consentBox, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.cnstPg)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 3, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.cnstPg)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.cnstPg)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 4, 1, 1)
        self.consentTitle = QtWidgets.QLabel(self.cnstPg)
        self.consentTitle.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.consentTitle.setPalette(palette)
        self.consentTitle.setAutoFillBackground(True)
        self.consentTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.consentTitle.setObjectName("consentTitle")
        self.gridLayout.addWidget(self.consentTitle, 0, 0, 1, 5)
        self.exitBox = QtWidgets.QPushButton(self.cnstPg)
        self.exitBox.setObjectName("exitBox")
        self.gridLayout.addWidget(self.exitBox, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.cnstPg)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 5)
        self.exp1All.addWidget(self.cnstPg)
        self.demogPg = QtWidgets.QWidget()
        self.demogPg.setObjectName("demogPg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.demogPg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.demogSubmit = QtWidgets.QPushButton(self.demogPg)
        self.demogSubmit.setObjectName("demogSubmit")
        self.gridLayout_2.addWidget(self.demogSubmit, 2, 0, 1, 2)
        self.consentTitle_3 = QtWidgets.QLabel(self.demogPg)
        self.consentTitle_3.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.consentTitle_3.setPalette(palette)
        self.consentTitle_3.setAutoFillBackground(True)
        self.consentTitle_3.setAlignment(QtCore.Qt.AlignCenter)
        self.consentTitle_3.setObjectName("consentTitle_3")
        self.gridLayout_2.addWidget(self.consentTitle_3, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.demogPg)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.nameQ = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.nameQ.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nameQ.setFont(font)
        self.nameQ.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameQ.setObjectName("nameQ")
        self.gridLayout_4.addWidget(self.nameQ, 0, 1, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.widget)
        self.txtName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtName.setObjectName("txtName")
        self.gridLayout_4.addWidget(self.txtName, 0, 2, 1, 2)
        self.nameE = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.nameE.setPalette(palette)
        self.nameE.setText("")
        self.nameE.setWordWrap(True)
        self.nameE.setObjectName("nameE")
        self.gridLayout_4.addWidget(self.nameE, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.emailQ = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.emailQ.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.emailQ.setFont(font)
        self.emailQ.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.emailQ.setObjectName("emailQ")
        self.gridLayout_4.addWidget(self.emailQ, 1, 1, 1, 1)
        self.emailBox = QtWidgets.QLineEdit(self.widget)
        self.emailBox.setObjectName("emailBox")
        self.gridLayout_4.addWidget(self.emailBox, 1, 2, 1, 2)
        self.emailE = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.emailE.setPalette(palette)
        self.emailE.setText("")
        self.emailE.setWordWrap(True)
        self.emailE.setObjectName("emailE")
        self.gridLayout_4.addWidget(self.emailE, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.genderQ = QtWidgets.QLabel(self.widget)
        self.genderQ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.genderQ.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.genderQ.setFont(font)
        self.genderQ.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.genderQ.setObjectName("genderQ")
        self.gridLayout_4.addWidget(self.genderQ, 2, 1, 1, 1)
        self.maleBtn = QtWidgets.QRadioButton(self.widget)
        self.maleBtn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.maleBtn.setObjectName("maleBtn")
        self.gridLayout_4.addWidget(self.maleBtn, 2, 2, 1, 1)
        self.femaleBtn = QtWidgets.QRadioButton(self.widget)
        self.femaleBtn.setObjectName("femaleBtn")
        self.gridLayout_4.addWidget(self.femaleBtn, 2, 3, 1, 1)
        self.genderE = QtWidgets.QLabel(self.widget)
        self.genderE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.genderE.setPalette(palette)
        self.genderE.setText("")
        self.genderE.setWordWrap(True)
        self.genderE.setObjectName("genderE")
        self.gridLayout_4.addWidget(self.genderE, 2, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.ageQ = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ageQ.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ageQ.setFont(font)
        self.ageQ.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ageQ.setObjectName("ageQ")
        self.gridLayout_4.addWidget(self.ageQ, 3, 1, 1, 1)
        self.ageBox = QtWidgets.QSpinBox(self.widget)
        self.ageBox.setObjectName("ageBox")
        self.gridLayout_4.addWidget(self.ageBox, 3, 2, 1, 1)
        self.ageE = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ageE.setPalette(palette)
        self.ageE.setText("")
        self.ageE.setWordWrap(True)
        self.ageE.setObjectName("ageE")
        self.gridLayout_4.addWidget(self.ageE, 3, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 4, 0, 1, 1)
        self.eduQ = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.eduQ.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.eduQ.setFont(font)
        self.eduQ.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.eduQ.setObjectName("eduQ")
        self.gridLayout_4.addWidget(self.eduQ, 4, 1, 1, 1)
        self.eduBox = QtWidgets.QComboBox(self.widget)
        self.eduBox.setObjectName("eduBox")
        self.eduBox.addItem("")
        self.eduBox.setItemText(0, "")
        self.eduBox.addItem("")
        self.eduBox.addItem("")
        self.eduBox.addItem("")
        self.eduBox.addItem("")
        self.gridLayout_4.addWidget(self.eduBox, 4, 2, 1, 2)
        self.eduE = QtWidgets.QLabel(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.eduE.setPalette(palette)
        self.eduE.setText("")
        self.eduE.setWordWrap(True)
        self.eduE.setObjectName("eduE")
        self.gridLayout_4.addWidget(self.eduE, 4, 4, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 2)
        self.exp1All.addWidget(self.demogPg)
        self.instr1Pg = QtWidgets.QWidget()
        self.instr1Pg.setObjectName("instr1Pg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.instr1Pg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.consentTitle_4 = QtWidgets.QLabel(self.instr1Pg)
        self.consentTitle_4.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.consentTitle_4.setPalette(palette)
        self.consentTitle_4.setAutoFillBackground(True)
        self.consentTitle_4.setAlignment(QtCore.Qt.AlignCenter)
        self.consentTitle_4.setObjectName("consentTitle_4")
        self.verticalLayout_3.addWidget(self.consentTitle_4)
        self.label_6 = QtWidgets.QLabel(self.instr1Pg)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.instrTxt = QtWidgets.QLabel(self.instr1Pg)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.instrTxt.setPalette(palette)
        self.instrTxt.setAutoFillBackground(True)
        self.instrTxt.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.instrTxt.setWordWrap(True)
        self.instrTxt.setObjectName("instrTxt")
        self.verticalLayout_3.addWidget(self.instrTxt)
        self.nxt1 = QtWidgets.QPushButton(self.instr1Pg)
        self.nxt1.setObjectName("nxt1")
        self.verticalLayout_3.addWidget(self.nxt1)
        self.exp1All.addWidget(self.instr1Pg)
        self.exp1 = QtWidgets.QWidget()
        self.exp1.setObjectName("exp1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.exp1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.error = QtWidgets.QLabel(self.exp1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.error.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.error.setFont(font)
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        self.gridLayout_6.addWidget(self.error, 0, 0, 1, 1)
        self.exp1Start = QtWidgets.QLabel(self.exp1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.exp1Start.setFont(font)
        self.exp1Start.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.exp1Start.setObjectName("exp1Start")
        self.gridLayout_6.addWidget(self.exp1Start, 1, 0, 1, 1)
        self.exp1All.addWidget(self.exp1)
        self.results1 = QtWidgets.QWidget()
        self.results1.setObjectName("results1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.results1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.inconRShow = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.inconRShow.setFont(font)
        self.inconRShow.setAutoFillBackground(True)
        self.inconRShow.setText("")
        self.inconRShow.setAlignment(QtCore.Qt.AlignCenter)
        self.inconRShow.setObjectName("inconRShow")
        self.gridLayout_3.addWidget(self.inconRShow, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 1, 1, 1)
        self.popConShow = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.popConShow.setFont(font)
        self.popConShow.setAutoFillBackground(True)
        self.popConShow.setText("")
        self.popConShow.setAlignment(QtCore.Qt.AlignCenter)
        self.popConShow.setObjectName("popConShow")
        self.gridLayout_3.addWidget(self.popConShow, 8, 2, 1, 1)
        self.stroopRShow = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.stroopRShow.setFont(font)
        self.stroopRShow.setAutoFillBackground(True)
        self.stroopRShow.setText("")
        self.stroopRShow.setAlignment(QtCore.Qt.AlignCenter)
        self.stroopRShow.setObjectName("stroopRShow")
        self.gridLayout_3.addWidget(self.stroopRShow, 6, 2, 1, 1)
        self.resultsNxt = QtWidgets.QPushButton(self.results1)
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.resultsNxt.setFont(font)
        self.resultsNxt.setObjectName("resultsNxt")
        self.gridLayout_3.addWidget(self.resultsNxt, 11, 0, 1, 5)
        self.popStroopShow = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.popStroopShow.setFont(font)
        self.popStroopShow.setAutoFillBackground(True)
        self.popStroopShow.setText("")
        self.popStroopShow.setAlignment(QtCore.Qt.AlignCenter)
        self.popStroopShow.setObjectName("popStroopShow")
        self.gridLayout_3.addWidget(self.popStroopShow, 10, 2, 1, 1)
        self.popInconShow = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.popInconShow.setFont(font)
        self.popInconShow.setAutoFillBackground(True)
        self.popInconShow.setText("")
        self.popInconShow.setAlignment(QtCore.Qt.AlignCenter)
        self.popInconShow.setObjectName("popInconShow")
        self.gridLayout_3.addWidget(self.popInconShow, 9, 2, 1, 1)
        self.conRShow = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.conRShow.setFont(font)
        self.conRShow.setAutoFillBackground(True)
        self.conRShow.setAlignment(QtCore.Qt.AlignCenter)
        self.conRShow.setObjectName("conRShow")
        self.gridLayout_3.addWidget(self.conRShow, 4, 2, 1, 1)
        self.results1Stats = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.results1Stats.setFont(font)
        self.results1Stats.setAlignment(QtCore.Qt.AlignCenter)
        self.results1Stats.setObjectName("results1Stats")
        self.gridLayout_3.addWidget(self.results1Stats, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 8, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 9, 1, 1, 1)
        self.consentTitle_5 = QtWidgets.QLabel(self.results1)
        self.consentTitle_5.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.consentTitle_5.setPalette(palette)
        self.consentTitle_5.setAutoFillBackground(True)
        self.consentTitle_5.setAlignment(QtCore.Qt.AlignCenter)
        self.consentTitle_5.setObjectName("consentTitle_5")
        self.gridLayout_3.addWidget(self.consentTitle_5, 0, 0, 2, 5)
        self.label_13 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 6, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 10, 1, 1, 1)
        self.resultsChart = QtWidgets.QLabel(self.results1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.resultsChart.setPalette(palette)
        self.resultsChart.setAutoFillBackground(True)
        self.resultsChart.setText("")
        self.resultsChart.setScaledContents(False)
        self.resultsChart.setObjectName("resultsChart")
        self.gridLayout_3.addWidget(self.resultsChart, 2, 4, 9, 1)
        self.buffer = QtWidgets.QLabel(self.results1)
        self.buffer.setText("")
        self.buffer.setObjectName("buffer")
        self.gridLayout_3.addWidget(self.buffer, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 1, 1, 1)
        self.partNumShow = QtWidgets.QLabel(self.results1)
        self.partNumShow.setMinimumSize(QtCore.QSize(58, 0))
        self.partNumShow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        self.partNumShow.setFont(font)
        self.partNumShow.setAutoFillBackground(True)
        self.partNumShow.setAlignment(QtCore.Qt.AlignCenter)
        self.partNumShow.setObjectName("partNumShow")
        self.gridLayout_3.addWidget(self.partNumShow, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.results1)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(14)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 7, 1, 1, 2)
        self.exp1All.addWidget(self.results1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.consentTitle_6 = QtWidgets.QLabel(self.page_2)
        self.consentTitle_6.setMaximumSize(QtCore.QSize(16777215, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.consentTitle_6.setPalette(palette)
        self.consentTitle_6.setAutoFillBackground(True)
        self.consentTitle_6.setAlignment(QtCore.Qt.AlignCenter)
        self.consentTitle_6.setObjectName("consentTitle_6")
        self.verticalLayout_4.addWidget(self.consentTitle_6)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.finishBtn = QtWidgets.QPushButton(self.page_2)
        self.finishBtn.setObjectName("finishBtn")
        self.verticalLayout_4.addWidget(self.finishBtn)
        self.exp1All.addWidget(self.page_2)
        self.gridLayout_5.addWidget(self.exp1All, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exp1All.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.wlcNext, self.demogSubmit)
        MainWindow.setTabOrder(self.demogSubmit, self.nxt1)
        MainWindow.setTabOrder(self.nxt1, self.resultsNxt)
        MainWindow.setTabOrder(self.resultsNxt, self.finishBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rr.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#21ff06;\">R</span></p></body></html>"))
        self.oo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#fd8008;\">O</span></p></body></html>"))
        self.wlcNext.setText(_translate("MainWindow", "Click Here To Continue"))
        self.pp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#6666ff;\">P</span></p></body></html>"))
        self.ss.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#fc0280;\">S</span></p></body></html>"))
        self.consentTitle_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; color:#e6e6e6;\">Welcome</span></p></body></html>"))
        self.tt.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#66ffff;\">T</span></p></body></html>"))
        self.OO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#ffff0a;\">O</span></p></body></html>"))
        self.task.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:64pt; color:#cccccc;\">TASK</span></p></body></html>"))
        self.consentBox.setText(_translate("MainWindow", "I Consent"))
        self.consentTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; color:#e6e6e6;\">Consent</span></p></body></html>"))
        self.exitBox.setText(_translate("MainWindow", "I DO NOT Consent"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">Thank you for your interest in taking part in this research. </span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">Before you agree to take part, please read the following carefully. </span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">By consenting , you agree with the Participant\'s Statements below:<br/></span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">1) I understand that if I decide at any time that I no longer wish to take part in this project, I can close the window and leave the survey immedately.</span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">2) I consent to the processing of my personal information for the purposes of this research study. </span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">3) I understand that such information will be treated as strictly confidential and handled in accordance with the provisions of the Data Protection Act 1998. </span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">4) I agree to be contacted in the future by UCL researchers who would like to invite me to participate in follow-up studies. </span></p><p align=\"center\"><span style=\" font-size:18pt; color:#e6e6e6;\">5) The information I provided in this study can be publically published, subject to removal of personal identifiers.</span></p></body></html>"))
        self.demogSubmit.setText(_translate("MainWindow", "Submit"))
        self.consentTitle_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; color:#e6e6e6;\">Demographics</span></p></body></html>"))
        self.nameQ.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#191919;\">Insert Name Here:</span></p></body></html>"))
        self.emailQ.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#191919;\">Insert Email Here:</span></p></body></html>"))
        self.genderQ.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#191919;\">Select your gender:</span></p></body></html>"))
        self.maleBtn.setText(_translate("MainWindow", "Male"))
        self.femaleBtn.setText(_translate("MainWindow", "Female"))
        self.ageQ.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#191919;\">Select your age:</span></p></body></html>"))
        self.eduQ.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#191919;\">Education Level:</span></p></body></html>"))
        self.eduBox.setItemText(1, _translate("MainWindow", "Post-Gradaute"))
        self.eduBox.setItemText(2, _translate("MainWindow", "Graduate"))
        self.eduBox.setItemText(3, _translate("MainWindow", "High School"))
        self.eduBox.setItemText(4, _translate("MainWindow", "None"))
        self.consentTitle_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">Instructions</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/><span style=\" font-size:14pt; color:#e6e6e6;\">In this task, you will see colour names (red, blue, green etc.) in different \'print\' colours. </span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">You need to respond to the print colour and not what the words say.</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">For example, if you see:</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#fc0107;\">green</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">You need to respond to the print colour (red), and press the associated button (\'r\').</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#21ff06;\">blue</span><span style=\" font-size:14pt; color:#e6e6e6;\">=&gt; press button &quot;g&quot;, because ink is green </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#fc0107;\">green</span><span style=\" font-size:14pt; color:#e6e6e6;\">=&gt; press button &quot;r&quot;, because ink is red </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff0a;\">yellow</span><span style=\" font-size:14pt; color:#e6e6e6;\">=&gt; press button &quot;y&quot;, because ink is yellow</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#0000ff;\">red</span><span style=\" font-size:14pt; color:#e6e6e6;\"> =&gt; press button &quot;b&quot;, because ink is blue</span></p><p align=\"center\"><span style=\" color:#e6e6e6;\">This task can be difficult, because the name and the ink color are conflicting (except for yellow in the example above). So concentrate and ignore the meaning of the color words, instead, look at the ink color. You get multiple trials and it takes around 5 minutes to complete. At the end, you get your response times. </span><br/></p></body></html>"))
        self.instrTxt.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\">Specifically, the buttons used in this study are:</p></body></html>"))
        self.nxt1.setText(_translate("MainWindow", "Next"))
        self.exp1Start.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#e6e6e6;\">Press any key to start</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">incongruent reaction time</span></p></body></html>"))
        self.resultsNxt.setText(_translate("MainWindow", "Next"))
        self.conRShow.setText(_translate("MainWindow", "330ms"))
        self.results1Stats.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">congruent reaction time</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">average congruent reaction time</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">average incongruent reaction time</span></p></body></html>"))
        self.consentTitle_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; color:#e6e6e6;\">Results</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">stroop score</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">average stroop score</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">You are participant No.</span></p></body></html>"))
        self.partNumShow.setText(_translate("MainWindow", "1"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Your average...</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">How others performed...</span></p></body></html>"))
        self.consentTitle_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; color:#e6e6e6;\">Debrief</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">Thank you for participating in this experiment. What you have just experienced is called a Stroop Task. </span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">The Stroop Effect is one of the best known phenomena in cognitive psychology. It is related to selective attention, which is the ability to respond to certain environmental stimuli while ignoring others. As you would have realised by now, it is very easy to name the color of the word &quot;red&quot; when it is printed in red ink color. It is difficult, though, when the word and the ink color are different! </span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">Even though this test was developed in the 1930s, the Stroop Task is still frequently used to measure how well people can do something that clashes with their typical response pattern. This task requires a certain level of &quot;mental control&quot;. That is, you need to be aware of the task you are doing now and ignore how you would normally respond to words. This requires \'control\' over your own default cognitive processing. The Stroop effect is essentially the degree of difficulty people have with naming the color of the ink rather than the word itself. The higher your Stroop Score, the greater the difficulty you have with \'incongruent\' word-visual stimuli.</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">In Stroop’s words, there is \'interference\' between the color of the ink and the word meaning. This interference occurs no matter how hard you try. It implies that at least part of our information processing occurs automatically, outside of conscious control.</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#e6e6e6;\">One of the explanations for the difficulty is that we are so used to processing word meaning while ignoring the physical features of words, that it is a learned response. The Stroop task requires us to do something which we have never learned and which is opposite what we normally do.</span></p></body></html>"))
        self.finishBtn.setText(_translate("MainWindow", "Fin"))

